# Generated by Django 5.1.6 on 2025-03-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
